### ISSUE TITLE
PHP 7.2 - headers have already been sent

### ISSUE THREAD

**Issue by C-Lodder** [joomla-framework/session#36]
### Steps to reproduce the issue

I've just updated the PHP version on one of my sites to 7.2 and now getting the following error:

> Failed to start the session because headers have already been sent by "/libraries/joomla/session/storage.php" at line 106.

### System information (as much as possible)

Joomla 3.8.5
PHP 7.2

### Additional comments

I know it's not much to go on. Perhaps the session framework package isn't PHP 7.2 ready?

**Comment by C-Lodder** [comment]
Hmm I think this may have been because I was still logged in when I updated PHP, so closing for now

**Comment by mbabker** [comment]
That's a CMS file path anyway 😉

To be honest, I don't know what kind of shape the 1.x code is in (and it's not in use in the CMS).  But 2.0 should run with no error on PHP 7.2 (and the 2.0 branch is used in the CMS 4.0 branch).
